- tags:
    - klipper
  become: true
  block:
    - name: Install system packages
      ansible.builtin.apt:
        name:
          # python cffi
          - libffi-dev
          # kconfig
          - libncurses-dev
          # hub-ctrl
          - libusb-dev
          # ARM chips
          - stm32flash
          - libnewlib-arm-none-eabi
          - gcc-arm-none-eabi
          - binutils-arm-none-eabi
          - libusb-1.0-0
          - pkg-config
        state: latest

    - become_user: "{{ klipper_user }}"
      block:
        - name: Clone klipper
          ansible.builtin.git:
            dest: "{{ install_base }}/klipper"
            repo: https://github.com/Klipper3d/klipper
            version: 1a24e7c5b683355335b115e5659eb6fe8c8d11dc
          register: install_result

        - name: Create virtualenv
          ansible.builtin.pip:
            requirements: "{{ install_base }}/klipper/scripts/klippy-requirements.txt"
            state: present
            virtualenv: "{{ install_base }}/venv/klippy"
            virtualenv_python: python3

        - name: Configure klipper
          ansible.builtin.copy:
            dest: "{{ install_base }}/printer_data/config/{{ item }}"
            src: "{{ item }}"
          loop:
            - klipper.cfg
            - mainsail.cfg
            - printer.cfg
          register: config_result

        - name: Configure firmware
          ansible.builtin.copy:
            dest: "{{ install_base }}/klipper/.config"
            src: firmware.config

    - name: Install systemd service
      ansible.builtin.template:
        dest: /etc/systemd/system/klipper.service
        src: klipper.service.j2
        owner: root
        group: root
        mode: "0644"
      register: service_result

    - name: Enable and start systemd service
      ansible.builtin.systemd:
        daemon_reload: true
        name: klipper
        state: "{{ 'restarted' if needs_restart else 'started' }}"
        enabled: true
      vars:
        needs_restart: "{{ [ install_result, config_result, service_result ] | select('changed') }}"
